AWSTemplateFormatVersion: '2010-09-09'
Description: 'OKR Tracker - Single instance deployment with Bedrock integration and S3 backups'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair for EC2 access

  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
    Description: EC2 instance type

  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-5-sonnet-20241022-v2:0
    Description: Bedrock model ID for Claude

  AllowedSSHCidr:
    Type: String
    Default: 10.0.0.0/8
    Description: CIDR block allowed for SSH access (use corporate VPN range or 10.0.0.0/8)

  DomainName:
    Type: String
    Default: ''
    Description: Domain name for SSL (e.g., okr.yourcompany.com). Leave empty for IP-only access.

  EnableSSL:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: Enable automatic SSL via Let's Encrypt (requires valid domain)

  BackupRetentionDays:
    Type: Number
    Default: 30
    Description: Number of days to retain database backups in S3

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c7217cdde317cfec
    us-west-2:
      AMI: ami-03f65b8614a860c29
    eu-west-1:
      AMI: ami-0905a3c97561e0b69
    eu-west-2:
      AMI: ami-0e8d228ad90af673b

Resources:
  # ============ S3 BACKUP BUCKET ============
  BackupBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}-backups-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldBackups
            Status: Enabled
            ExpirationInDays: !Ref BackupRetentionDays
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 7
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-backups'

  # ============ IAM ROLE ============
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                  - bedrock:ListFoundationModels
                Resource: '*'
        - PolicyName: S3BackupAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !GetAtt BackupBucket.Arn
                  - !Sub '${BackupBucket.Arn}/*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-profile'
      Roles:
        - !Ref EC2Role

  # ============ SECURITY GROUP ============
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName}-sg'
      GroupDescription: Security group for OKR Tracker
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedSSHCidr
          Description: SSH access
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP access
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS access
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-sg'

  # ============ ELASTIC IP ============
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-eip'

  # ============ EC2 INSTANCE ============
  EC2Instance:
    Type: AWS::EC2::Instance
    DependsOn: BackupBucket
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref SecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 30
            VolumeType: gp3
            DeleteOnTermination: false
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -e
          exec > >(tee /var/log/user-data.log) 2>&1

          echo "Starting OKR Tracker setup..."

          # Update system
          apt-get update && apt-get upgrade -y

          # Install Docker
          curl -fsSL https://get.docker.com | sh
          usermod -aG docker ubuntu

          # Install Docker Compose
          apt-get install -y docker-compose-plugin

          # Install tools
          apt-get install -y git curl wget htop jq awscli postgresql-client

          # Install Node.js 20
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

          # Create app directory
          mkdir -p /opt/okr-tracker
          chown ubuntu:ubuntu /opt/okr-tracker

          # Clone repository
          su - ubuntu -c "git clone https://github.com/berryk/okr-tracker.git /opt/okr-tracker"

          # Create .env file
          cd /opt/okr-tracker
          JWT_SECRET=$(openssl rand -hex 32)
          PUBLIC_IP=$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4)

          cat > .env <<EOF
          JWT_SECRET=$JWT_SECRET
          CORS_ORIGIN=http://$PUBLIC_IP
          VITE_API_URL=http://$PUBLIC_IP
          LLM_PROVIDER=bedrock
          AWS_REGION=${AWS::Region}
          BEDROCK_MODEL_ID=${BedrockModelId}
          DB_PASSWORD=okr_password
          BACKUP_BUCKET=${BackupBucket}
          EOF

          chown ubuntu:ubuntu .env

          # ============ BACKUP SCRIPT ============
          cat > /opt/okr-tracker/backup.sh <<'BACKUP_SCRIPT'
          #!/bin/bash
          set -e

          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          BACKUP_FILE="okr_backup_$TIMESTAMP.sql.gz"
          BUCKET="${BackupBucket}"
          REGION="${AWS::Region}"

          echo "[$TIMESTAMP] Starting database backup..."

          # Dump database from Docker container
          docker exec okr-tracker-db-1 pg_dump -U okr okr_tracker | gzip > /tmp/$BACKUP_FILE

          # Upload to S3
          aws s3 cp /tmp/$BACKUP_FILE s3://$BUCKET/daily/$BACKUP_FILE --region $REGION

          # Clean up local file
          rm /tmp/$BACKUP_FILE

          # Keep only last 7 daily backups locally described in S3
          echo "[$TIMESTAMP] Backup uploaded to s3://$BUCKET/daily/$BACKUP_FILE"

          # Also create a "latest" copy for easy restore
          aws s3 cp s3://$BUCKET/daily/$BACKUP_FILE s3://$BUCKET/latest/okr_latest.sql.gz --region $REGION

          echo "[$TIMESTAMP] Backup complete!"
          BACKUP_SCRIPT

          chmod +x /opt/okr-tracker/backup.sh
          chown ubuntu:ubuntu /opt/okr-tracker/backup.sh

          # ============ RESTORE SCRIPT ============
          cat > /opt/okr-tracker/restore.sh <<'RESTORE_SCRIPT'
          #!/bin/bash
          set -e

          BUCKET="${BackupBucket}"
          REGION="${AWS::Region}"

          if [ -z "$1" ]; then
            echo "Usage: ./restore.sh <backup-file.sql.gz | latest>"
            echo "Example: ./restore.sh okr_backup_20260123_030000.sql.gz"
            echo "         ./restore.sh latest"
            exit 1
          fi

          if [ "$1" == "latest" ]; then
            S3_PATH="s3://$BUCKET/latest/okr_latest.sql.gz"
          else
            S3_PATH="s3://$BUCKET/daily/$1"
          fi

          echo "Downloading backup from $S3_PATH..."
          aws s3 cp $S3_PATH /tmp/restore.sql.gz --region $REGION

          echo "Restoring database..."
          gunzip -c /tmp/restore.sql.gz | docker exec -i okr-tracker-db-1 psql -U okr okr_tracker

          rm /tmp/restore.sql.gz
          echo "Restore complete!"
          RESTORE_SCRIPT

          chmod +x /opt/okr-tracker/restore.sh
          chown ubuntu:ubuntu /opt/okr-tracker/restore.sh

          # ============ CRON JOB FOR DAILY BACKUPS ============
          # Run backup at 3 AM daily
          echo "0 3 * * * ubuntu /opt/okr-tracker/backup.sh >> /var/log/okr-backup.log 2>&1" > /etc/cron.d/okr-backup
          chmod 644 /etc/cron.d/okr-backup

          # ============ START APPLICATION ============
          su - ubuntu -c "cd /opt/okr-tracker && docker compose -f docker-compose.aws.yml up -d"

          # Wait for services
          sleep 30

          # Initialize database
          su - ubuntu -c "cd /opt/okr-tracker && docker compose -f docker-compose.aws.yml exec -T backend npx prisma db push" || true
          su - ubuntu -c "cd /opt/okr-tracker && docker compose -f docker-compose.aws.yml exec -T backend npx prisma db seed" || true

          # Run initial backup
          /opt/okr-tracker/backup.sh || true

          echo "OKR Tracker setup complete with S3 backups enabled!"

  # ============ ELASTIC IP ASSOCIATION ============
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance
      EIP: !Ref ElasticIP

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !Ref EC2Instance

  PublicIP:
    Description: Elastic IP address
    Value: !Ref ElasticIP

  WebURL:
    Description: URL to access OKR Tracker
    Value: !Sub 'http://${ElasticIP}'

  SSHCommand:
    Description: SSH command to connect
    Value: !Sub 'ssh -i ~/.ssh/${KeyName}.pem ubuntu@${ElasticIP}'

  SSMConnect:
    Description: Connect via Session Manager (no SSH key needed)
    Value: !Sub 'aws ssm start-session --target ${EC2Instance} --region ${AWS::Region}'

  BackupBucket:
    Description: S3 bucket for database backups
    Value: !Ref BackupBucket

  BackupCommand:
    Description: Manual backup command
    Value: '/opt/okr-tracker/backup.sh'

  RestoreCommand:
    Description: Restore from latest backup
    Value: '/opt/okr-tracker/restore.sh latest'

  ListBackups:
    Description: List available backups
    Value: !Sub 'aws s3 ls s3://${BackupBucket}/daily/ --region ${AWS::Region}'

  DemoCredentials:
    Description: Demo login credentials
    Value: 'Email: ceo@demo.com | Password: demo123'
